### ISSUE TITLE
I want to ask a question

### ISSUE THREAD

**Issue by fffffddddaaas** [hxwork/OMNet_Pytorch#13]
I meet a error: "FileNotFoundError".  Do you know how to solve?
<img width="868" alt="微信图片_20240509153831" src="https://github.com/hxwork/OMNet_Pytorch/assets/169342714/4dea7551-b0e0-4da1-927f-0c5741d1b11b">

**Comment by hxwork** [comment]
Please find the solution [here](https://github.com/hxwork/OMNet_Pytorch/issues/8#issuecomment-1288139256).

**Comment by fffffddddaaas** [comment]
Thank you very much. With what you have said, I have solved the problem.
