### ISSUE TITLE
CAN'T DOWNLOAD THE DATASET TS.ZIP

### ISSUE THREAD

**Issue by Sabershou** [hxwork/OMNet_Pytorch#5]
您好，我是浙江大学学生，对您这篇文章的内容非常感兴趣，但是下载不了您提到的两个数据集，显示网页不存在，可以麻烦您数据集发至我的邮箱吗？syj12125092@zju.edu.cn

**Comment by hxwork** [comment]
Hi,

Thanks for your interest. I have updated the download link in README, and you can download it now.
