### ISSUE TITLE
shape_names.txt error in ModelNetNpy

### ISSUE THREAD

**Issue by ExistLi777** [hxwork/OMNet_Pytorch#8]
Hello, I want to train with the modelnet_os dataset you provided. The error in ModelNetNpy is because there is no shape_names.txt problem in modelnet_os, （My network always breaks downloading the modelnet_ts dataset and I do not download the dataset.） so how should I modify the class ModelNetNpy?

**Comment by hxwork** [comment]
Hi,

Thanks for your interest. We use the `shape_names.txt` in the original ModelNet40 dataset. Sorry that I forgot to put it into the `modelnet_os`. I directly put it here for your convenience. You can create that file manually.
```
airplane
bathtub
bed
bench
bookshelf
bottle
bowl
car
chair
cone
cup
curtain
desk
door
dresser
flower_pot
glass_box
guitar
keyboard
lamp
laptop
mantel
monitor
night_stand
person
piano
plant
radio
range_hood
sink
sofa
stairs
stool
table
tent
toilet
tv_stand
vase
wardrobe
xbox
```

**Comment by ExistLi777** [comment]
嘿嘿，谢谢大哥这么晚的回复~我在我电脑上试了一下应该是可以了。明天我去服务器上试一下。
